language: python
python:
- 3.6.6
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest -vs tests/
env:
- TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR
before_install:
- echo "$PATH"
- echo "$TRAVIS_BUILD_DIR"
notifications:
- email: false
deploy:
  provider: pypi
  user: mwanakijiji
  password:
    secure: M62TCgA2vrGCr2pTakRFM4/Cdm1c83/DO23Q2Oi+oPs1a4BfiHAjoZ937l1v0YPwp2aTgF08BJ9zxfkO1+TgpaeqlLvgydKrPBxaw0K2awB8jj+6vmJwdg+dgrvcaBNldjqRucVBMAn1VAjV/2bxdXjdEy0Kv9PJqhAQRiB0eL5NgBiutNTVerljEA1tnMyzNhV5Y8F3aABJbexE21K5jH8YZ0ROouM1xIqPVDKKlvM4TPum+Yqr/dVCqw2H8lY9c9PiSkJlg/oi8oUm0BMrjUpVxekZz6TPKhq4352RnxJjJzf8kBjkAy/N6JEqeuhzWXwy3gHpaIGFDKnwv75G0D4Zf5fPmM39w8mXH7ADJKWZzSDYj9epyk3QG0LOF7y3lEuwQbn9skeW0IJ1Sy6xN7mCz1EpfVX3HSQUvptox637/CJpST2AR4cvSZeF1LmFWunvqLRXPtyAbtmOGjA6NjbZLdJxG/mPKVy4gugNw5JULnUjkE1pdhgz1ntgm3UtOUEMSskV4KpYtlNuV0n3eyPDvGqC2oFc9+0Yco/uxmMpCzFisjzgdRP7jEurrlAA9N/zHN5my/ec3mgN/LexKKv2FvYUEdf0XDsM54iiTSpczWSW0UWHkjXhF+mkfIPlNs+ZplB8ikJGRV6fiF/ZdXYg8hb8yxeHpeeHZ2nx/pI=
